import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ExternalLink, ShieldAlert } from "lucide-react";
export type RiskStatus = { rule_version: string; limits: Record<string, string | number>; recent_rejections: Array<Record<string, string>> };
export type ComplianceStatus = { policy_state: string; sources: Array<Record<string, string | null>>; features: Array<{ feature: string; allowed: boolean; blocked_reasons: string[] }> };
export type AuditStatus = { state: string; findings: Array<{ finding_id: string; finding_type: string; severity: string; owner_department: string; resolution_state: string; evidence: string[]; snapshots: Array<{ snapshot_id: string; evidence_link: string }> }> };
type Props = { view: "xingbu" | "libu" | "dongchang"; loadRisk?: () => Promise<RiskStatus>; loadCompliance?: () => Promise<ComplianceStatus>; loadAudit?: () => Promise<AuditStatus>; complianceAction?: (source: string, action: "authorize" | "revoke" | "acknowledge") => Promise<void> };
export function GovernanceView(props: Props) {
  const [data, setData] = useState<RiskStatus | ComplianceStatus | AuditStatus | null>(null); const [error, setError] = useState("");
  useEffect(() => { setData(null); setError(""); const loader = props.view === "xingbu" ? props.loadRisk : props.view === "libu" ? props.loadCompliance : props.loadAudit; if (!loader) { setError("服务未配置"); return; } void loader().then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "服务不可用")); }, [props.view, props.loadRisk, props.loadCompliance, props.loadAudit]);
  if (error) return <main className="command-center"><section className="governance-page"><div className="error-state" role="alert"><AlertTriangle />{error}</div></section></main>;
  if (!data) return <main className="command-center"><section className="governance-page">正在加载...</section></main>;
  if (props.view === "xingbu") { const risk = data as RiskStatus; return <main className="command-center"><section className="governance-page"><header><p className="eyebrow">刑部 / XINGBU</p><h1>实时风控</h1><span className="policy-badge">规则 {risk.rule_version}</span></header><div className="governance-grid">{Object.entries(risk.limits).map(([key, value]) => <div className="governance-unit" key={key}><small>{key}</small><b>{value}</b></div>)}</div><h2>近期拒绝</h2>{risk.recent_rejections.length === 0 ? <p className="no-audit">暂无拒绝记录</p> : risk.recent_rejections.map((item) => <article className="finding-row" key={item.decision_id}><ShieldAlert /><div><b>{item.symbol} / {item.reason_code}</b><small>{item.rule_version} · {item.order_id}</small></div></article>)}</section></main>; }
  if (props.view === "libu") { const policy = data as ComplianceStatus; return <main className="command-center"><section className="governance-page"><header><p className="eyebrow">礼部 / LIBU</p><h1>来源权限与声明</h1>{policy.policy_state === "stale" && <span className="policy-badge warning">政策需复核</span>}</header>{policy.sources.map((source) => <article className="permission-row" key={source.source ?? "source"}><div><b>{source.source}</b><small>{source.permission_state} · 声明 {source.disclaimer_version} · {source.user_acknowledged_at ? "已确认" : "未确认"}</small></div><div className="action-row"><button onClick={() => void props.complianceAction?.(String(source.source), "authorize")}>授权</button><button onClick={() => void props.complianceAction?.(String(source.source), "acknowledge")}>确认声明</button><button className="danger-action" onClick={() => void props.complianceAction?.(String(source.source), "revoke")}>撤销授权</button></div></article>)}{policy.features.map((feature) => <div className={`feature-state ${feature.allowed ? "allowed" : "blocked"}`} key={feature.feature}>{feature.allowed ? <CheckCircle2 /> : <ShieldAlert />}<div><b>{feature.feature}</b><small>{feature.allowed ? "可用" : feature.blocked_reasons.join(", ")}</small></div></div>)}</section></main>; }
  const audit = data as AuditStatus; return <main className="command-center"><section className="governance-page"><header><p className="eyebrow">东厂 / DONGCHANG</p><h1>独立审计发现</h1></header>{audit.findings.length === 0 ? <p className="no-audit">暂无审计发现</p> : audit.findings.map((finding) => <article className={`audit-finding ${finding.severity}`} key={finding.finding_id}><div className="finding-heading"><b>{finding.finding_type}</b><span>{finding.severity.toUpperCase()}</span></div><p>责任部门：{finding.owner_department} · {finding.resolution_state}</p>{finding.snapshots.map((snapshot) => <div className="snapshot-link" key={snapshot.snapshot_id}><ExternalLink size={14} /><span>{snapshot.evidence_link}</span></div>)}</article>)}</section></main>;
}
